#!/bin/sh

gitroot="$(gitroot)"
if [ $gitroot ]; then cd "$gitroot"; else cd ..; fi

src=$(find "$(pwd)" -mindepth 2 -maxdepth 2 -name README.rst)
dst=$(pwd)/$name

sphinxter "$src" | pandoc -f html -t $format -o "$dst"

afplay /System/Library/Sounds/Glass.aiff 2> /dev/null
growlnotify -t $name -m "$(userpath "$dst")" -i $i 2> /dev/null
